version: '3.3'
services:
    # Nginx Service
    webserver:
        container_name: nginx
        build:
            context: ./
            dockerfile: ./nginx/Dockerfile
        restart: unless-stopped
        tty: true
        volumes: 
            - ../:/var/www
        ports: 
            - 1234:80
        networks:
            - laravel-web-socket

    # PHP Service
    php:
        container_name: php_fpm
        build: 
            context: ./
            dockerfile: ./php/Dockerfile
        tty: true
        volumes:
            - ../:/var/www
        ports: 
            - 6001:6001     # Laravel WebSockets Port
        links: 
            - mysql
        networks: 
            - laravel-web-socket
        # command: "php artisan migrate:fresh --seed"
    
    # Node.js Service
    node:
        container_name: node
        build: 
            context: ./
            dockerfile: ./node/Dockerfile
        tty: true
        volumes: 
            - ../:/var/www
        # command: ['npm', 'run', 'dev']   # ['npm', 'run', 'watch-poll']
        networks:
            - laravel-web-socket
    
    # MySQL Service
    mysql:
        container_name: db
        image: mysql:5.7
        restart: unless-stopped
        tty: true
        volumes: 
            - ./mysql/my.cnf:/etc/mysql/my.cnf
            - ./mysql/volumes:/var/logs/mysql
            # - ./mysql/volumes:/var
            # - ./mysql/logs:/var/logs
        ports: 
            - 33060:3306
        expose: 
            - 3306
        environment: 
            - MYSQL_DATABASE=laravel_web_socket
            - MYSQL_ROOT_PASSWORD=laravelDocker
        networks: 
            - laravel-web-socket

    # Redis Service
    redis:
        container_name: redis
        image: redis:latest
        restart: unless-stopped
        ports: 
            - 6378:6379
        networks: 
            - laravel-web-socket

# Docker Networks
networks: 
    laravel-web-socket:
        driver: bridge
            